INSERT INTO [dbo].[custinfo] ([code], [name], [address], [city], [mobile], [email]) VALUES (N'100', N'SHIVAM SHARMA', N'PATNA', N'PATNA', N'1234567890', N'qwer@in.com')
INSERT INTO [dbo].[custinfo] ([code], [name], [address], [city], [mobile], [email]) VALUES (N'101', N'NAGENDRA SINGH', N'ANANDPURI', N'muzaffarpur', N'987654321', N'rewq@ni.com')
INSERT INTO [dbo].[custinfo] ([code], [name], [address], [city], [mobile], [email]) VALUES (N'102', N'DEEPAK SINGH', N'B B GANJ', N'MUZAFFARPUR', N'32542', N'fdfa')
INSERT INTO [dbo].[custinfo] ([code], [name], [address], [city], [mobile], [email]) VALUES (N'103', N'DIYA SINMGH', N'ANANDPURI', N'MUZAFFARPUR', N'12245555', N'KKKK@201200')
INSERT INTO [dbo].[custinfo] ([code], [name], [address], [city], [mobile], [email]) VALUES (N'104', N'D K SINGH', N'ANANDPURI', N'MUZAFFARPUR', N'14524555', N'HHHHH@1255')
